"""2

Revision ID: 48f326ca4fde
Revises: 80857b9625f3
Create Date: 2018-05-26 08:14:16.525275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f326ca4fde'
down_revision = '80857b9625f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsibilities', schema=None) as batch_op:
        batch_op.drop_constraint('UC_teacher_id_post_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsibilities', schema=None) as batch_op:
        batch_op.create_unique_constraint('UC_teacher_id_post_id', ['teacher_id', 'resp_id'])

    # ### end Alembic commands ###
