"""init

Revision ID: 80857b9625f3
Revises: 
Create Date: 2018-05-22 16:49:25.557938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80857b9625f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hours_per_month', sa.Float(), nullable=True),
    sa.Column('months_per_year', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsibility_name'), 'responsibility', ['name'], unique=True)
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('grades', sa.Boolean(), nullable=True),
    sa.Column('hs', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_first_name'), 'teacher', ['first_name'], unique=False)
    op.create_index(op.f('ix_teacher_last_name'), 'teacher', ['last_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('weeks', sa.Float(), nullable=True),
    sa.Column('min_per_week', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=True)
    op.create_table('responsibilities',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('resp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resp_id'], ['responsibility.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'resp_id'),
    sa.UniqueConstraint('teacher_id', 'resp_id', name='UC_teacher_id_post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsibilities')
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_teacher_last_name'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_first_name'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_responsibility_name'), table_name='responsibility')
    op.drop_table('responsibility')
    # ### end Alembic commands ###
