"""test

Revision ID: ab4b0a0a819b
Revises: ec58947321ba
Create Date: 2018-06-10 10:10:42.576232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4b0a0a819b'
down_revision = 'ec58947321ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('course_teacher_id_fkey', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('course_teacher_id_fkey', 'teacher', ['teacher_id'], ['id'])

    # ### end Alembic commands ###
